"""Compatibility facade for the built-in Kimi K3 checkpoint normalizer."""

from omiv.model_packs.kimi_k3.checkpoint import (
    DENSE_COMPONENTS,
    DENSE_RE,
    DESCRIPTOR_ENTITY_EXAMPLE_CAP,
    EXPERT_RE,
    KDA_MARKERS,
    LAYER_RE,
    LAYER_RESIDUAL_RE,
    MLA_MARKERS,
    MODEL_RESIDUAL_RE,
    MOE_NAMESPACE_RE,
    SELF_ATTN_RE,
    SHARED_RE,
    UNCLASSIFIED_EXAMPLES_PER_GROUP_CAP,
    UNCLASSIFIED_GROUP_CAP,
    iter_raw_records,
    normalize_inventory,
    write_inventory,
)

__all__ = [
    "DENSE_COMPONENTS",
    "DENSE_RE",
    "DESCRIPTOR_ENTITY_EXAMPLE_CAP",
    "EXPERT_RE",
    "KDA_MARKERS",
    "LAYER_RE",
    "LAYER_RESIDUAL_RE",
    "MLA_MARKERS",
    "MODEL_RESIDUAL_RE",
    "MOE_NAMESPACE_RE",
    "SELF_ATTN_RE",
    "SHARED_RE",
    "UNCLASSIFIED_EXAMPLES_PER_GROUP_CAP",
    "UNCLASSIFIED_GROUP_CAP",
    "iter_raw_records",
    "normalize_inventory",
    "write_inventory",
]
